---
title: "kontextual"
output: html_document
date: "2025-10-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#LINK VIGNETTA 
https://www.bioconductor.org/packages/devel/bioc/vignettes/Statial/inst/doc/Statial.html
```{r}
library(Statial)
library(spicyR)
library(ClassifyR)
library(lisaClust)
library(dplyr)
library(SingleCellExperiment)
library(ggplot2)
library(ggsurvfit)
library(survival)
library(tibble)
library(treekoR)
```

Analizziamo la questione Trim - Endothelials / Trim - FAPs
come contesto: myo2b / tutti i myo

#Defining the hierarchy
```{r}
nuclei_list_ann <- readRDS("~/nuclei_list_ann.rds")

biologicalHierarchy <- list(
  "myonuclei" = c("Myonuclei_MTJ", "Myonuclei_Trim63", "Myonuclei_IIb",
                  "Myonuclei_IIx_IIb", "Myonuclei_IIx",
                  "Myonuclei_NMJ", "Myonuclei_IIx_IIa"),
  "stromal"   = c("Endothelial", "FAPs", "Pericyte", "Smooth_Muscular", "Tenocyte"),
  "rare"      = c("MuSC", "Nervous_System", "Immune_Cells")
)

```


```{r}
# spe <- nuclei_list_ann$blocco2_c26
# spe <- nuclei_list_ann$blocco4_c26
# spe <- nuclei_list_ann$blocco6_c26
# 
# spe$celltype_kontextual <- spe$cell_type
# spe$celltype_kontextual[spe$cell_type %in% biologicalHierarchy$myonuclei] <- "Myonuclei"
# spe$celltype_kontextual[spe$cell_type == "Myonuclei_Trim63"] <- "Myonuclei_Trim63"
# spe$celltype_kontextual <- as.factor(spe$celltype_kontextual)
# table(spe$celltype_kontextual)
# 
# #il raggio è nella stessa unità delle coordinate (quindi in um)
# #perché è una soglia posta sulla distanza euclidea degli spot (che hanno le coordinate in pixel)
# curves <- kontextCurve(
#   cells = spe,
#   from = "Immune_Cells",
#   to = "Myonuclei_Trim63",
#   parent = c("Myonuclei_Trim63", "Myonuclei"),
#   rs = seq(5, 50, 5),
#   cellType = "celltype_kontextual",
#   spatialCoords = c("pxl_col_in_fullres", "pxl_row_in_fullres"),
#   imageID = "sample_id",
#   #inhom = TRUE
# )
# kontextPlot(curves)
# 
# curves <- kontextCurve(
#   cells = spe,
#   from = "Endothelial",
#   to = "Myonuclei_Trim63",
#   parent = c("Myonuclei_Trim63", "Myonuclei"),
#   rs = seq(10, 100, 10),
#   cellType = "celltype_kontextual",
#   spatialCoords = c("pxl_col_in_fullres", "pxl_row_in_fullres"),
#   imageID = "sample_id",
#   #inhom = TRUE
# )
# kontextPlot(curves)
# 
# curves <- kontextCurve(
#   cells = spe,
#   from = "FAPs",
#   to = "Myonuclei_Trim63",
#   parent = c("Myonuclei_Trim63", "Myonuclei"),
#   rs = seq(10, 100, 10),
#   cellType = "celltype_kontextual",
#   spatialCoords = c("pxl_col_in_fullres", "pxl_row_in_fullres"),
#   imageID = "sample_id",
#   #inhom = TRUE
# )
# kontextPlot(curves)

```

```{r}
# Define samples and cell types
samples <- c("blocco2_c26", "blocco4_c26", "blocco6_c26")

from_types <- c("Endothelial", "FAPs", "Pericyte", "Smooth_Muscular",
                "Tenocyte", "MuSC", "Nervous_System", "Immune_Cells")
dir.create("plots_kontext", showWarnings = FALSE)

# Loop over samples
for (s in samples) {
  
  spe <- nuclei_list_ann[[s]]
  
  # Create contextual cell type once
  spe$celltype_kontextual <- spe$cell_type
  spe$celltype_kontextual[spe$cell_type %in% biologicalHierarchy$myonuclei] <- "Myonuclei"
  spe$celltype_kontextual[spe$cell_type == "Myonuclei_Trim63"] <- "Myonuclei_Trim63"
  spe$celltype_kontextual <- as.factor(spe$celltype_kontextual)
  
  # Loop over "from" cell types
  for (ct in from_types) {
    
    curves <- kontextCurve(
      cells = spe,
      from = ct,
      to = "Myonuclei_Trim63",
      parent = c("Myonuclei_Trim63", "Myonuclei"),
      rs = seq(5, 50, 5),
      cellType = "celltype_kontextual",
      spatialCoords = c("pxl_col_in_fullres", "pxl_row_in_fullres"),
      imageID = "sample_id"
    )
  
    p <- kontextPlot(curves)
    filename <- paste0("kontext_", s, "_from_", ct, ".png")
    ggsave(filename, plot = p, width = 8, height = 6)
  }
}
```

