---
title: "MuSC"
output: html_document
date: "2025-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(arrow)
library(Banksy)
library(BiocParallel)
library(DropletUtils)
library(dplyr)
library(edgeR)
library(ggplot2)
library(graphics)
library(igraph)
library(jsonlite)
library(Matrix)
library(matrixStats)
library(OSTA.data)
library(patchwork)
library(pheatmap)
library(S4Vectors)
library(scDblFinder)
library(scater)
library(scran)
library(scuttle)
library(SingleCellExperiment)
library(SpatialExperiment)
library(SummarizedExperiment)
library(tidyr)
library(VisiumIO)
library(spacexr)
library(SpotSweeper)
library(ggspavis)
library(openxlsx)
library(zip)
library(clusterProfiler)
library(org.Mm.eg.db)
```

#Faccio una cosa sensata: uso i DEGs e semmai rilasso le condizioni
#parto da c26 vs sham dei nuclei che è il confronto con + DEG
```{r}
pb <- readRDS("~/pb_16bin.rds")
lrt_list <- list()
summary_list <- list()

celltype <- "MuSC"
ct_pb <- pb[, pb$new_cell_type == celltype]

y <- DGEList(counts(ct_pb), samples = as.data.frame(colData(ct_pb)))
#RILASSO UN PO' LE CONDIZIONI DI FILTRAGGIO DEI GENI
set.seed(72625)
keep <- filterByExpr(
  y,
  group = y$samples$tissue_type,
  min.count = 1,
  min.total.count = 1
)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y, method="TMM")

design <- model.matrix(~ 0 + tissue_type, y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)

contrast_list <- list(
  C26_vs_SHAM   = "tissue_typec26 - tissue_typesham",
  MURF1_vs_SHAM = "tissue_typec26murf1 - tissue_typesham",
  MURF1_vs_C26 = "tissue_typec26murf1 - tissue_typec26"
)

for (contrast_name in names(contrast_list)) {
  
  contrast <- makeContrasts(
    contrasts = contrast_list[[contrast_name]],
    levels = design
  )
  
  lrt <- glmLRT(fit, contrast = contrast)
  res <- topTags(lrt, n = Inf)$table
  res$SYMBOL <- rownames(res)
  res$significant <- res$FDR < 0.05
    
  sig <- res[res$significant, ]
  sig_up <- sig[sig$logFC >= 0, ]
  sig_down <- sig[sig$logFC < 0, ]
    
  lrt_list[[contrast_name]] <- list(
    full = res,
    sig = sig,
    up = sig_up,
    down = sig_down
  )
    
  gene_summary <- data.frame(
    contrast = contrast_name,
    cell_type = celltype,
    Geni_considerati = nrow(res),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
  )
    
  summary_list[[length(summary_list) + 1]] <- gene_summary
}

summary_df <- do.call(rbind, summary_list)
print(summary_df)

```

#salvo i DEG
```{r}
top <- lrt_list$MURF1_vs_SHAM$full
wb <- createWorkbook()
addWorksheet(wb, "Tutti_geni")
writeData(wb, "Tutti_geni", top, rowNames = TRUE)
addWorksheet(wb, "Significativi")
writeData(wb, "Significativi", sig, rowNames = TRUE)
addWorksheet(wb, "Upregolati")
writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
addWorksheet(wb, "Downregolati")
writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
saveWorkbook(wb,"musc_murf_sham.xlsx", overwrite = TRUE)

top <- lrt_list$C26_vs_SHAM$full
wb <- createWorkbook()
addWorksheet(wb, "Tutti_geni")
writeData(wb, "Tutti_geni", top, rowNames = TRUE)
addWorksheet(wb, "Significativi")
writeData(wb, "Significativi", sig, rowNames = TRUE)
addWorksheet(wb, "Upregolati")
writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
addWorksheet(wb, "Downregolati")
writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
saveWorkbook(wb,"musc_c26_sham.xlsx", overwrite = TRUE)

top <- lrt_list$MURF1_vs_C26$full
wb <- createWorkbook()
addWorksheet(wb, "Tutti_geni")
writeData(wb, "Tutti_geni", top, rowNames = TRUE)
addWorksheet(wb, "Significativi")
writeData(wb, "Significativi", sig, rowNames = TRUE)
addWorksheet(wb, "Upregolati")
writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
addWorksheet(wb, "Downregolati")
writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
saveWorkbook(wb,"musc_murf_c26.xlsx", overwrite = TRUE)
```

#GSEA C26 VS SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("c26"), 1, 0)

top <- lrt_list$C26_vs_SHAM$full
rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_MuSC_c26_sham.xlsx", overwrite = TRUE)

```

#GSEA MURF VS SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("c26murf1"), 1, 0)

top <- lrt_list$MURF1_vs_SHAM$full
rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_MuSC_murf1_sham.xlsx", overwrite = TRUE)

```

#GSEA MURF VS C26
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("c26murf1"), 1, 0)

top <- lrt_list$MURF1_vs_C26$full
rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_MuSC_murf1_c26.xlsx", overwrite = TRUE)

```


#Creo un oggetto spatial unico e indago se i MuSC aumentano tra c26 e sham
```{r}
for (nm in names(subset_list)) {
  spe <- subset_list[[nm]]
  colData(spe)$sample_id <- rep(nm, ncol(spe))  
  subset_list[[nm]] <- spe
}

spe_list <- subset_list[names(subset_list)]
exclude_names <- c("sham_b7", "c26STAT3_b7", "c26_b7")
combined_spe_wob7 <- do.call(
  cbind, 
  spe_list[!(names(spe_list) %in% exclude_names)]
)
table(colData(combined_spe_wob7)$sample_id)

rm(subset_list)
#REMOVING NAs
keep <- !is.na(combined_spe_wob7$cell_type)
combined_spe_wob7[,keep]
save(combined_spe_wob7, file="combined_spe_wob7.RData")

table(combined_spe_wob7$cell_type=="MuSC",combined_spe_wob7$tissue_type)
prop.table(table(combined_spe_wob7$cell_type=="MuSC",combined_spe_wob7$tissue_type))
#sono di più negli sham che nei c26 e molte di più nei trattamenti (torna!)
table(combined_spe_wob7$cell_type=="MuSC",combined_spe_wob7$sample_id)

#Modello binomiale per testare l'effetto della condizione
y <- ifelse(combined_spe_wob7$cell_type=="MuSC",1,0)

combined_spe_wob7$tissue_type <- relevel(combined_spe_wob7$tissue_type, ref = "sham")

mod_mixed <- glmer(
  I(cell_type == "MuSC") ~ tissue_type + (1 | sample_id),
  data = as.data.frame(colData(combined_spe_wob7)),
  family = binomial
)

summary(mod_mixed) 
#si confermano le previsioni: con c26 diminuiscono rispetto a sham e con i trattamenti aumentano

#visualizzazione?
y <- prop.table(table(combined_spe_wob7$cell_type=="MuSC",combined_spe_wob7$sample_id))[2,]
x <- c(rep("c26",3),rep("c26fox0",4),rep("c26murf1",4),rep("c26SMAD23",4),rep("c26STAT3",3),rep("sham",3))
x <- as.factor(x)
png("boxplot.png", width = 800, height = 600, res = 120)
boxplot(y ~ x)
```

#Dotplot
```{r}
pb <- readRDS("~/pb_16bin.rds")

pb_musc <- pb[,pb$new_cell_type == "MuSC"]
pb_musc_rid <- pb_musc[,pb_musc$tissue_type %in% c("sham", "c26", "c26murf1")]

genes <- c("Pax7","Myod1","Myog","Myf6")

expr <- assay(pb_musc_rid, "counts")
expr_sub <- expr[genes, ]
df <- as.data.frame(t(expr_sub))
df$sampletype <- pb_musc_rid$tissue_type

# Long format
df_long <- df %>%
  pivot_longer(cols = all_of(genes), 
               names_to = "gene", 
               values_to = "expression")

# Summary: media + percentuale espressione
df_sum <- df_long %>%
  group_by(sampletype, gene) %>%
  summarise(
    avg_exp = mean(expression),
    pct_exp = mean(expression > 0) * 100,
    .groups = "drop"
  )

df_sum <- df_sum %>%
  mutate(sampletype = factor(sampletype,
                             levels = c("sham", "c26", "c26murf1")))

p <- ggplot(df_sum, aes(x = sampletype, y = gene)) +
  geom_point(aes(size = pct_exp, color = avg_exp)) +
  scale_color_gradient(low = "grey80", high = "red") +
  theme_minimal() +
  labs(x = "Sample type", y = "Gene") +
  theme(
    panel.grid = element_blank(),
    axis.line = element_line(color = "black"),  
    axis.ticks = element_line(color = "black"), 
    axis.text.x = element_text(angle = 45, hjust = 1),
    text = element_text(size = 14),
  )
ggsave("dotplot_musc.pdf", plot = p,
       width = 6, height = 4, dpi = 300)
```




