---
title: "MuSC_nuclei"
output: html_document
date: "2026-03-27"
---

---
title: "MuSC"
output: html_document
date: "2025-11-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(arrow)
library(Banksy)
library(BiocParallel)
library(DropletUtils)
library(dplyr)
library(edgeR)
library(ggplot2)
library(graphics)
library(igraph)
library(jsonlite)
library(Matrix)
library(matrixStats)
library(OSTA.data)
library(patchwork)
library(pheatmap)
library(S4Vectors)
library(scDblFinder)
library(scater)
library(scran)
library(scuttle)
library(SingleCellExperiment)
library(SpatialExperiment)
library(SummarizedExperiment)
library(tidyr)
library(VisiumIO)
library(spacexr)
library(SpotSweeper)
library(ggspavis)
library(openxlsx)
library(zip)
library(clusterProfiler)
library(org.Mm.eg.db)
```

#MuSC annotation correction
MuSC are defined as cells where Pax7 gene is expressed.
```{r}
# nuclei_list <- readRDS("~/nuclei_list_ann.rds")
# 
# nuclei_list <- lapply(nuclei_list, function(spe) {
#   print(table(spe$cell_type == "MuSC"))
#   pax7_pos <- counts(spe)["Pax7", ] > 0
#   spe$cell_type[pax7_pos] <- "MuSC"
#   print(table(spe$cell_type == "MuSC"))
#   return(spe)
# })

#qua la signature è già giusta! cambiano al massimo di 1
```

#Faccio una cosa sensata: uso i DEGs e semmai rilasso le condizioni
#parto da c26 vs sham dei nuclei che è il confronto con + DEG
```{r}
pb <- readRDS("~/pb_nuclei.rds")

lrt_list <- list()
summary_list <- list()

celltype <- "MuSC"
ct_pb <- pb[, pb$cell_type == celltype]

y <- DGEList(counts(ct_pb), samples = as.data.frame(colData(ct_pb)))
#RILASSO UN PO' LE CONDIZIONI DI FILTRAGGIO DEI GENI
set.seed(72625)
keep <- filterByExpr(
  y,
  group = y$samples$sampletype,
  min.count = 5,
  min.total.count = 10
)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y, method="TMM")

design <- model.matrix(~ 0 + sampletype, y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)

contrast_list <- list(
  C26_vs_SHAM   = "sampletypec26 - sampletypesham",
  MURF1_vs_SHAM = "sampletypec26murf1 - sampletypesham",
  MURF1_vs_C26 = "sampletypec26murf1 - sampletypec26"
)

for (contrast_name in names(contrast_list)) {
  
  contrast <- makeContrasts(
    contrasts = contrast_list[[contrast_name]],
    levels = design
  )
  
  lrt <- glmLRT(fit, contrast = contrast)
  res <- topTags(lrt, n = Inf)$table
  res$SYMBOL <- rownames(res)
  res$significant <- res$FDR < 0.05
    
  sig <- res[res$significant, ]
  sig_up <- sig[sig$logFC >= 0, ]
  sig_down <- sig[sig$logFC < 0, ]
    
  lrt_list[[contrast_name]] <- list(
    full = res,
    sig = sig,
    up = sig_up,
    down = sig_down
  )
    
  gene_summary <- data.frame(
    contrast = contrast_name,
    cell_type = celltype,
    Geni_considerati = nrow(res),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
  )
    
  summary_list[[length(summary_list) + 1]] <- gene_summary
}

summary_df <- do.call(rbind, summary_list)
print(summary_df)

```

#GSEA C26 VS SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("c26"), 1, 0)

top <- lrt_list$C26_vs_SHAM$full
rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_MuSC_c26_sham_nuclei.xlsx", overwrite = TRUE)

```

#GSEA MURF VS SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("c26murf1"), 1, 0)

top <- lrt_list$MURF1_vs_SHAM$full
rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_MuSC_murf1_sham_nuclei.xlsx", overwrite = TRUE)

```

#GSEA MURF VS C26
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("c26murf1"), 1, 0)

top <- lrt_list$MURF1_vs_C26$full
rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_MuSC_murf1_c26_nuclei.xlsx", overwrite = TRUE)

```

#se vuole vedere i geni
```{r}
top <- lrt_list$MURF1_vs_SHAM$full
wb <- createWorkbook()
addWorksheet(wb, "Tutti_geni")
writeData(wb, "Tutti_geni", top, rowNames = TRUE)
addWorksheet(wb, "Significativi")
writeData(wb, "Significativi", sig, rowNames = TRUE)
addWorksheet(wb, "Upregolati")
writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
addWorksheet(wb, "Downregolati")
writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
saveWorkbook(wb,"musc_murf_sham.xlsx", overwrite = TRUE)

top <- lrt_list$C26_vs_SHAM$full
wb <- createWorkbook()
addWorksheet(wb, "Tutti_geni")
writeData(wb, "Tutti_geni", top, rowNames = TRUE)
addWorksheet(wb, "Significativi")
writeData(wb, "Significativi", sig, rowNames = TRUE)
addWorksheet(wb, "Upregolati")
writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
addWorksheet(wb, "Downregolati")
writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
saveWorkbook(wb,"musc_c26_sham.xlsx", overwrite = TRUE)

top <- lrt_list$MURF1_vs_C26$full
wb <- createWorkbook()
addWorksheet(wb, "Tutti_geni")
writeData(wb, "Tutti_geni", top, rowNames = TRUE)
addWorksheet(wb, "Significativi")
writeData(wb, "Significativi", sig, rowNames = TRUE)
addWorksheet(wb, "Upregolati")
writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
addWorksheet(wb, "Downregolati")
writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
saveWorkbook(wb,"musc_murf_c26.xlsx", overwrite = TRUE)
```
