---
title: "GSEA"
output: html_document
date: "2025-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(SingleCellExperiment)
library(SummarizedExperiment)
library(scuttle)
library(edgeR)
library(RUVSeq)
library(scMerge)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(openxlsx)
library(dplyr)
library(stringr)
library(AnnotationDbi)
library(pathview)
library(muscat)
library(org.Mm.eg.db)
library(patchwork)
```

#Objects and functions
```{r}
pb <- readRDS("~/data/pb_16bin.rds")

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}

contrast_list <- list(
  "C26_vs_SHAM"   = c("tissue_typec26 - tissue_typesham"),
  "STAT3_vs_C26"  = c("tissue_typec26STAT3 - tissue_typec26"),
  "STAT3_vs_SHAM" = c("tissue_typec26STAT3 - tissue_typesham")
)

```

# TRIM C26 VS 2B SHAM 
```{r}
pb$group <- paste0(pb$new_cell_type, "_", pb$tissue_type)
pb_sub <- pb[, pb$group %in% c("Myonuclei_Trim63_c26", "Myonuclei_IIb_sham")]
pb_sub$group <- factor(pb_sub$group, levels = c("Myonuclei_IIb_sham", "Myonuclei_Trim63_c26"))

y <- DGEList(counts(pb_sub), samples = as.data.frame(colData(pb_sub)))
keep <- filterByExpr(y, group = y$samples$group)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
design <- model.matrix(~ group, data=y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = 2)
top <- topTags(lrt, n = Inf)$table
top$SYMBOL <- rownames(top)

top$significant <- top$FDR < 0.05
sig <- top[top$significant, ]
sig_up <- sig[sig$logFC >= 0, ]
sig_down <- sig[sig$logFC < 0, ]
  
gene_summary <- data.frame(
    Geni_considerati = nrow(top),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
)
  
gene_summary
  
```

#GSEA TRIM C26 VS 2B SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$tissue_type == "c26", 1, 0)

rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]
geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)

res_df 
# wb <- createWorkbook()
# addWorksheet(wb, "GSEA_Results")
# writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
# saveWorkbook(wb, file = "gsea_trim_2b.xlsx", overwrite = TRUE)

```

#subset pathways interessanti
```{r}
 pathways <- c("mmu04260", "mmu00190", "mmu04261", "mmu04714", "mmu04713",
  "mmu04020", "mmu04310", "mmu04820", "mmu05208", "mmu04140",
  "mmu04141", "mmu04210", "mmu03008", "mmu04668", "mmu04115",
  "mmu04064", "mmu03050", "mmu04610")

gsea_sig@result <- gsea_sig@result[gsea_sig@result$ID %in% pathways,]
```

#DOTPLOT GSEA TRIM C26 VS 2B SHAM
```{r}
p <- enrichplot::dotplot(gsea_sig, showCategory = 15, font.size = 8,
                    title = "Enriched Pathways", split=".sign") + facet_grid(.~.sign)
ggsave("pathways_trim_2b.pdf", plot = p,
       width = 8, height = 9, dpi = 300)

#second plot 
enrich_KEGG <- as.data.frame(gsea_sig@result)
enrich_KEGG <- enrich_KEGG[order(enrich_KEGG$p.adjust), ]
enrich_KEGG <- enrich_KEGG[enrich_KEGG$p.adjust < 0.05, ]

enrich_KEGG$Count <- sapply(strsplit(enrich_KEGG$core_enrichment, "/"), length)
enrich_KEGG$GeneRatio <- enrich_KEGG$Count / enrich_KEGG$setSize

#enrich_KEGG <- head(enrich_KEGG, 35)
# p2 <- ggplot(enrich_KEGG,
#                             aes(x = -log10(p.adjust),
#                                 y = reorder(Description, -log10(p.adjust)),
#                                 color = GeneRatio,
#                                 size = Count)) +
#   geom_point() +
#   scale_color_gradient(low = "blue", high = "red") +
#   theme_minimal(base_size = 10) +
#   ylab("Description") +
#   xlab("-log10(p.adjust)") +
#   ggtitle("Top 35 KEGG")
# 
# p2

# separa i dati
enrich_pos <- enrich_KEGG[enrich_KEGG$NES > 0, ]
enrich_neg <- enrich_KEGG[enrich_KEGG$NES < 0, ]

# grafico positivi
p_pos <- ggplot(enrich_pos,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Positive Pathways")

ggsave("trim_2b_pos.pdf", plot = p_pos,
       width = 20, height = 9, dpi = 300)

# grafico negativi
p_neg <- ggplot(enrich_neg,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Negative Pathways")

ggsave("trim_2b_neg.pdf", plot = p_neg,
       width = 20, height = 9, dpi = 300)

```

# TRIM C26 VS MYONUCLEI OVERALL SHAM
```{r}
pb$group <- paste0(pb$new_cell_type, "_", pb$tissue_type)
mio_ov_sham <- unique(grep(paste0("^", "Myonuclei", ".*", "sham"), pb$group, value = TRUE))
pb_sub <- pb[, pb$group %in% c("Myonuclei_Trim63_c26", mio_ov_sham)]
pb_sub$group[pb_sub$group %in% mio_ov_sham] <- "Myonuclei_sham"
pb_sub$group <- as.factor(pb_sub$group)
pb_comb <- aggregateData(pb_sub, assay = "counts", fun = "sum", by = "sample_id")
colData(pb_comb)$group <- pb_sub$group[match(colnames(pb_comb), pb_sub$sample_id)]
names(assays(pb_comb)) <- "counts"

y <- DGEList(counts(pb_comb), samples = as.data.frame(colData(pb_comb)))
keep <- filterByExpr(y, group = y$samples$group)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
design <- model.matrix(~ group, data=y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = 2)
top <- topTags(lrt, n = Inf)$table
top$SYMBOL <- rownames(top)

top$significant <- top$FDR < 0.05
sig <- top[top$significant, ]
sig_up <- sig[sig$logFC >= 0, ]
sig_down <- sig[sig$logFC < 0, ]

gene_summary <- data.frame(
    Geni_considerati = nrow(top),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
)
  
gene_summary
  
```

#GSEA TRIM C26 VS MYONUCLEI OVERALL SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == "Myonuclei_Trim63_c26", 1, 0)

rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]
geneList <- make_geneList_kegg(geneList)

gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE)
gsea_sig@result

gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)
res_df <- as.data.frame(gsea_sig@result)

# wb <- createWorkbook()
# addWorksheet(wb, "GSEA_Results")
# writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
# saveWorkbook(wb, file = "gsea_trim_overall.xlsx", overwrite = TRUE)

```

#subset pathways interessanti
```{r}
pathways_trim_overall <- c("mmu03050", "mmu04061", "mmu04610", "mmu03060", "mmu03008",
  "mmu04140", "mmu04141", "mmu04064", "mmu04137", "mmu04210",
  "mmu03040", "mmu04142", "mmu04360", "mmu04024", "mmu04371",
  "mmu04022", "mmu04020", "mmu04814", "mmu04261", "mmu04820",
  "mmu04512", "mmu00760", "mmu04714", "mmu04976", "mmu00020",
  "mmu00190", "mmu04260")

gsea_sig@result <- gsea_sig@result[gsea_sig@result$ID %in% pathways_trim_overall,]
```

#DOTPLOT GSEA TRIM C26 VS MYONUCLEI OVERALL SHAM
```{r}
p <- enrichplot::dotplot(gsea_sig, showCategory = 50, font.size = 8,
                    title = "Enriched Pathways", split=".sign") + facet_grid(.~.sign)
ggsave("pathways_trim_overall.pdf", plot = p,
       width = 8, height = 9, dpi = 300)

#second plot 
enrich_KEGG <- as.data.frame(gsea_sig@result)
enrich_KEGG <- enrich_KEGG[order(enrich_KEGG$p.adjust), ]
enrich_KEGG <- enrich_KEGG[enrich_KEGG$p.adjust < 0.05, ]

enrich_KEGG$Count <- sapply(strsplit(enrich_KEGG$core_enrichment, "/"), length)
enrich_KEGG$GeneRatio <- enrich_KEGG$Count / enrich_KEGG$setSize

#enrich_KEGG <- head(enrich_KEGG, 15)
# p2 <- ggplot(enrich_KEGG,
#                             aes(x = -log10(p.adjust),
#                                 y = reorder(Description, -log10(p.adjust)),
#                                 color = GeneRatio,
#                                 size = Count)) +
#   geom_point() +
#   scale_color_gradient(low = "blue", high = "red") +
#   theme_minimal(base_size = 16) +
#   ylab("Description") +
#   xlab("-log10(p.adjust)") +
#   ggtitle("Top 15 KEGG")
# 
# p2

enrich_pos <- enrich_KEGG[enrich_KEGG$NES > 0, ]
enrich_neg <- enrich_KEGG[enrich_KEGG$NES < 0, ]

# grafico positivi
p_pos <- ggplot(enrich_pos,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Positive Pathways")

ggsave("trim_overall_pos.pdf", plot = p_pos,
       width = 20, height = 9, dpi = 300)

# grafico negativi
p_neg <- ggplot(enrich_neg,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Negative Pathways")

ggsave("trim_overall_neg.pdf", plot = p_neg,
       width = 20, height = 9, dpi = 300)

```

#GSEA ALL CELLTYPES
```{r message = FALSE, warning = FALSE}

gsea_list <- list()

for (contrast_name in names(contrast_list)){
  wb <- createWorkbook()
  gsea_list[[contrast_name]] <- list()
  
  for (celltype in unique(pb$new_cell_type)){
    ct_pb <- pb[, pb$new_cell_type == celltype]
    y <- DGEList(counts(ct_pb), samples = as.data.frame(colData(ct_pb)))
    keep <- filterByExpr(y, group = y$samples$tissue_type)
    y <- y[keep,, keep.lib.sizes=FALSE]
    y <- calcNormFactors(y, method="TMM")
    design <- model.matrix(~ 0 + tissue_type, y$samples)
    y <- estimateDisp(y, design)
    se <- SummarizedExperiment(assays = list(counts = y$counts),
                               colData = y$samples)
    assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
    fit <- glmFit(y, design)
    contrast <- makeContrasts(contrasts = contrast_list[[contrast_name]], levels = design)
    lrt <- glmLRT(fit, contrast = contrast)
    top <- topTags(lrt, n = Inf)$table
    top$SYMBOL <- rownames(top)
    rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
    rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
    rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
    rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]
    
    #GSEA
    geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
    geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]
    geneList <- make_geneList_kegg(geneList)
    gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE)
    gsea_list[[contrast_name]][[celltype]] <- gsea_sig

if (!is.null(gsea_sig) && nrow(gsea_sig@result) > 0) {
  gsea_sig@result$core_enrichment_symbols <-
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)
  res_df <- as.data.frame(gsea_sig@result)
  sheet_name <- substr(gsub("[^[:alnum:]]", "_", celltype), 1, 31)
  addWorksheet(wb, sheetName = sheet_name)
  writeData(wb, sheet = sheet_name, res_df)
}
  }
  saveWorkbook(wb, paste0("GSEA_", contrast_name, ".xlsx"), overwrite = TRUE)
}

```

#SUBSET FOR THE PLOT
```{r}
end_c26_sham <- c("mmu00190", "mmu04714", "mmu01100", "mmu04610", "mmu00020", 
              "mmu04020", "mmu01200", "mmu04060", "mmu03050", "mmu04064", 
              "mmu00010", "mmu04061", "mmu00270", "mmu04210", "mmu04925", 
              "mmu04657", "mmu01230", "mmu04630")

faps_c26_sham <- c(
  "mmu00190", "mmu04714", "mmu04610", "mmu04020", "mmu00020",
  "mmu04060", "mmu03050", "mmu01200", "mmu04911", "mmu04064",
  "mmu04512", "mmu04510", "mmu00260", "mmu04024", "mmu04613",
  "mmu04623", "mmu04022", "mmu00010", "mmu04630", "mmu04750",
  "mmu04925", "mmu01230", "mmu04518", "mmu04142", "mmu04657",
  "mmu04672", "mmu04540", "mmu01210"
)

myo2b_c26_sham <- c("mmu03050", "mmu04142", "mmu04137", "mmu04140", "mmu04210",
  "mmu04657", "mmu04066", "mmu04610", "mmu04714", "mmu04510",
  "mmu04820", "mmu04020", "mmu00190", "mmu04260", "mmu04512",
  "mmu04360", "mmu04022", "mmu04810", "mmu04750", "mmu04024",
  "mmu04015", "mmu04518", "mmu04517", "mmu04010", "mmu04725")
  
myo2x2a_c26_sham <- c("mmu04714", "mmu03050", "mmu04610", "mmu04141", "mmu04820",
  "mmu00190", "mmu04260", "mmu04723", "mmu04814", "mmu05169",
  "mmu05171", "mmu05415", "mmu04142", "mmu04020", "mmu04145",
  "mmu04971", "mmu04022", "mmu03060", "mmu04380", "mmu05208",
  "mmu00480", "mmu04015")

myo2x_c26_sham <- c("mmu03050", "mmu04610", "mmu04141", "mmu03008", "mmu00480",
  "mmu04657", "mmu04820", "mmu04714", "mmu04261", "mmu04020",
  "mmu04510", "mmu04371", "mmu04512", "mmu04022", "mmu04750",
  "mmu04919", "mmu04310", "mmu00190", "mmu04814", "mmu04024",
  "mmu04658")

myo2x2b_c26_sham <- c("mmu04714", "mmu04820", "mmu04261", "mmu00190", "mmu04020",
  "mmu04814", "mmu04610", "mmu03050", "mmu04141", "mmu04142",
  "mmu04060", "mmu03008", "mmu04657", "mmu04140", "mmu04979",
  "mmu04920", "mmu04613")

myomtj_c26_sham <- c("mmu04714", "mmu00190", "mmu04723", "mmu04020", "mmu01100",
  "mmu04022", "mmu04261", "mmu04510", "mmu00480", "mmu04142",
  "mmu03050", "mmu04210", "mmu03008", "mmu00020")

trim_c26_sham <- 
  c("mmu03050", "mmu00190", "mmu01200", "mmu04137", "mmu04714",
  "mmu00020", "mmu00280", "mmu01210", "mmu00640", "mmu00620",
  "mmu04140", "mmu04152", "mmu00071", "mmu04066", "mmu03015",
  "mmu03040", "mmu03320", "mmu04068", "mmu04120", "mmu00630",
  "mmu01230", "mmu04218", "mmu01212", "mmu00380", "mmu04514",
  "mmu04061")

mappatura <- list(
  Endothelial       = end_c26_sham,
  FAPs              = faps_c26_sham,
  Myonuclei_IIb     = myo2b_c26_sham,
  Myonuclei_IIx_IIa = myo2x2a_c26_sham,
  Myonuclei_IIx     = myo2x_c26_sham,
  Myonuclei_IIx_IIb = myo2x2b_c26_sham,
  Myonuclei_MTJ     = myomtj_c26_sham,
  Myonuclei_Trim63  = trim_c26_sham
)

for (cluster in names(mappatura)) {
  ids <- mappatura[[cluster]]
  gsea_list$C26_vs_SHAM[[cluster]]@result <- subset(gsea_list$C26_vs_SHAM[[cluster]]@result, ID %in% ids)
}

```

#DOTPLOT GSEA ALL CELLTYPES
```{r message = FALSE, warning = FALSE}
#gsea_sig <- gsea_list$C26_vs_SHAM$Endothelial

for (contrast in names(gsea_list)) {
  
  pdf(paste0("GSEA_", contrast, ".pdf"), width = 16, height = 12)
  
  for (cell_type in names(gsea_list[[contrast]])) {
    
    gsea_sig <- gsea_list[[contrast]][[cell_type]]
    
    # skip se vuoto
    if (is.null(gsea_sig) || nrow(as.data.frame(gsea_sig@result)) == 0) next
    
    # --- DOTPLOT ---
    p1 <- enrichplot::dotplot(
      gsea_sig,
      showCategory = 30,
      font.size = 8,
      title = paste("Enriched Pathways -", contrast, "-", cell_type),
      split = ".sign"
    ) + facet_grid(. ~ .sign)
    
    # --- DATA ---
    enrich_KEGG <- as.data.frame(gsea_sig@result)
    enrich_KEGG <- enrich_KEGG[order(enrich_KEGG$p.adjust), ]
    enrich_KEGG <- enrich_KEGG[enrich_KEGG$p.adjust < 0.05, ]
    
    if (nrow(enrich_KEGG) == 0) next
    
    enrich_KEGG$Count <- sapply(strsplit(enrich_KEGG$core_enrichment, "/"), length)
    enrich_KEGG$GeneRatio <- enrich_KEGG$Count / enrich_KEGG$setSize
    
    enrich_pos <- enrich_KEGG[enrich_KEGG$NES > 0, ]
    enrich_neg <- enrich_KEGG[enrich_KEGG$NES < 0, ]
    enrich_pos <- enrich_pos[order(enrich_pos$p.adjust), ][1:min(20, nrow(enrich_pos)), ]
    enrich_neg <- enrich_neg[order(enrich_neg$p.adjust), ][1:min(20, nrow(enrich_neg)), ]

    # --- POS ---
    if (nrow(enrich_pos) > 0) {
      p2 <- ggplot(enrich_pos,
                   aes(x = -log10(p.adjust),
                       y = reorder(Description, -log10(p.adjust)),
                       color = GeneRatio,
                       size = Count)) +
        geom_point() +
        scale_color_gradient(low = "blue", high = "red") +
        theme_minimal(base_size = 14) +
        labs(title = paste("KEGG Positive -", cell_type))
    } else {
      p2 <- ggplot() + ggtitle("No positive pathways") + theme_void()
    }
    
    # --- NEG ---
    if (nrow(enrich_neg) > 0) {
      p3 <- ggplot(enrich_neg,
                   aes(x = -log10(p.adjust),
                       y = reorder(Description, -log10(p.adjust)),
                       color = GeneRatio,
                       size = Count)) +
        geom_point() +
        scale_color_gradient(low = "blue", high = "red") +
        theme_minimal(base_size = 14) +
        labs(title = paste("KEGG Negative -", cell_type))
    } else {
      p3 <- ggplot() + ggtitle("No negative pathways") + theme_void()
    }
    
    # --- COMBINA ---
    combined_plot <- (p1 / (p2 | p3))
    
    print(combined_plot)  # → nuova pagina nel PDF
  }
  
  dev.off()
}

```




