---
title: "DEG GFP nuclei"
output: html_document
date: "2026-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(arrow)
library(Banksy)
library(BiocParallel)
library(DropletUtils)
library(dplyr)
library(edgeR)
library(ggplot2)
library(graphics)
library(igraph)
library(jsonlite)
library(Matrix)
library(matrixStats)
library(OSTA.data)
library(patchwork)
library(pheatmap)
library(S4Vectors)
library(scDblFinder)
library(scater)
library(scran)
library(scuttle)
library(SingleCellExperiment)
library(SpatialExperiment)
library(SummarizedExperiment)
library(tidyr)
library(VisiumIO)
library(spacexr)
library(SpotSweeper)
library(ggspavis)
library(openxlsx)
library(spatialreg)
library(spdep)
library(spaMM)
library(scales) 
library(purrr)
```

#objects
```{r}
bin16_list_ann <- readRDS("~/bin16_list_ann_gfp.rds")
murf_list <- bin16_list_ann[names(bin16_list_ann) %in%
                                   c("c26murf1_b2", "c26murf1_b3", "c26murf1_b5", "c26murf1_b9")]
fox0_list <- bin16_list_ann[names(bin16_list_ann) %in%
                              c("c26foxO_b1","c26foxO_b4","c26foxO_b6","c26foxO_b9")]
smad_list <- bin16_list_ann[names(bin16_list_ann) %in%
                              c("c26SMAD23_b2","c26SMAD23_b4","c26SMAD23_b5","c26SMAD23_b9")]

murf_list$c26murf1_b2$to_discard <- NULL
smad_list$c26SMAD23_b2$to_discard <- NULL
murf_list$c26murf1_b3$gfp_value <- NULL
murf_list$c26murf1_b5$gfp_value <- NULL
murf_list$c26murf1_b9$gfp_value <- NULL
smad_list$c26SMAD23_b4$gfp_value <- NULL
smad_list$c26SMAD23_b5$gfp_value <- NULL
smad_list$c26SMAD23_b9$gfp_value <- NULL
murf_list$c26murf1_b2$in_treatment <- ifelse(murf_list$c26murf1_b2$in_treatment == TRUE, 1, 0)
smad_list$c26SMAD23_b2$in_treatment <- ifelse(smad_list$c26SMAD23_b2$in_treatment == TRUE, 1, 0)

# Define cell types
myonuclei_types <- c("Myonuclei_IIb", "Myonuclei_IIx",
                     "Myonuclei_IIx_IIa", "Myonuclei_IIx_IIb",
                     "Myonuclei_MTJ", "Myonuclei_NMJ", "Myonuclei_Trim63")

```

#function to create a combined_spe object
```{r}
prepare_pseudobulk <- function(spe_list, cell_types) {
  
  # Add sample identifiers
  for (nm in names(spe_list)) {
    spe <- spe_list[[nm]]
    colData(spe)$sample_id <- rep(nm, ncol(spe))
    spe_list[[nm]] <- spe
  }
  
  # Combine all samples
  combined_spe <- do.call(cbind, spe_list)
  print(table(combined_spe$sample_id, combined_spe$in_treatment))
  
  # Convert treatment to labels
  combined_spe$in_treatment <- ifelse(combined_spe$in_treatment == 1, "gfp+", "untreated")
  
  # Filter to specified cell types
  filtered_spe <- combined_spe[, combined_spe$new_cell_type %in% cell_types]
  
  # Create pseudo-bulk
  pb <- aggregateAcrossCells(filtered_spe, use.assay.type = "counts",
                             id = DataFrame(label = filtered_spe$in_treatment,
                                          sample = filtered_spe$sample_id))
  
  # Rename columns
  colnames(pb) <- paste(pb$in_treatment, pb$sample_id, sep = "_")
  
  return(pb)
}
```

#function to find DEGs
Non tiene conto della dipendenza tra treated e untreated nello stesso campione
Ma se aggiungessi semplicemente un effetto casuale per campione?
```{r}
run_de_analysis <- function(pb, fdr_threshold = 0.05, output_file = NULL) {

  y <- DGEList(counts(pb), samples = colData(pb))
  
  #Filter by expression
  keep <- filterByExpr(y, group = y$samples$in_treatment)
  y <- y[keep, , keep.lib.sizes = FALSE]
  
  # Normalize
  y <- calcNormFactors(y)
  
  # Set up treatment factor
  y$samples$in_treatment <- as.factor(y$samples$in_treatment)
  y$samples$in_treatment <- relevel(y$samples$in_treatment, ref = "untreated")
  
  # Design and fit
  design <- model.matrix(~ in_treatment, data = y$samples)
  y <- estimateDisp(y, design)
  fit <- glmFit(y, design)
  lrt <- glmLRT(fit, coef = "in_treatmentgfp+")
  
  # Get results
  res <- topTags(lrt, n = Inf)$table
  res$SYMBOL <- rownames(res)
  res$significant <- res$FDR < fdr_threshold
  
  # Separate significant genes
  sig <- res[res$significant, ]
  sig_up <- sig[sig$logFC >= 0, ]
  sig_down <- sig[sig$logFC < 0, ]
  
  # Summary
  gene_summary <- data.frame(
    Geni_considerati = nrow(res),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
  )
  
  print(gene_summary)
  
  # Export to Excel if filename provided
  if (!is.null(output_file)) {
    wb <- createWorkbook()
    addWorksheet(wb, "Tutti_geni")
    writeData(wb, "Tutti_geni", res, rowNames = TRUE)
    addWorksheet(wb, "Significativi")
    writeData(wb, "Significativi", sig, rowNames = TRUE)
    addWorksheet(wb, "Upregolati")
    writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
    addWorksheet(wb, "Downregolati")
    writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
    saveWorkbook(wb, output_file, overwrite = TRUE)
    cat("Results saved to:", output_file, "\n")
  }
  
  # Return results list
  return(list(
    dge = y,
    results = res,
    significant = sig,
    upregulated = sig_up,
    downregulated = sig_down,
    summary = gene_summary
  ))
}
```

#filtraggio geni
```{r}
# for (nm in names(murf_list)) {
#     spe <- murf_list[[nm]]
#     colData(spe)$sample_id <- rep(nm, ncol(spe))
#     murf_list[[nm]] <- spe
# }
# combined_spe <- do.call(cbind, murf_list)
# filtered_spe <- combined_spe[, combined_spe$new_cell_type %in% myonuclei_types]
# enough <- counts(filtered_spe) > 0
# keep_murf <- rowSums(enough) > 1000
# table(keep_murf) #2345
# 
# for (nm in names(fox0_list)) {
#     spe <- fox0_list[[nm]]
#     colData(spe)$sample_id <- rep(nm, ncol(spe))
#     fox0_list[[nm]] <- spe
# }
# combined_spe <- do.call(cbind, fox0_list)
# filtered_spe <- combined_spe[, combined_spe$new_cell_type %in% myonuclei_types]
# enough <- counts(filtered_spe) > 0
# keep_fox0 <- rowSums(enough) > 1000
# table(keep_fox0) #2891
# 
# for (nm in names(smad_list)) {
#     spe <- smad_list[[nm]]
#     colData(spe)$sample_id <- rep(nm, ncol(spe))
#     smad_list[[nm]] <- spe
# }
# combined_spe <- do.call(cbind, smad_list)
# filtered_spe <- combined_spe[, combined_spe$new_cell_type %in% myonuclei_types]
# enough <- counts(filtered_spe) > 0
# keep_smad <- rowSums(enough) > 1000
# table(keep_smad) #2499

```


#running the code for the three conditions
```{r}
pb_murf <- prepare_pseudobulk(murf_list, myonuclei_types)
#pb_murf <- pb_murf[keep_murf,]
de_results <- run_de_analysis(pb_murf, output_file = "myo_murf_gfp_DEGs.xlsx")

pb_fox0 <- prepare_pseudobulk(fox0_list, myonuclei_types)
#pb_fox0 <- pb_fox0[keep_fox0,]
de_results <- run_de_analysis(pb_fox0, output_file = "myo_fox0_gfp_DEGs.xlsx")
#NO SIG

pb_smad <- prepare_pseudobulk(smad_list, myonuclei_types)
#pb_smad <- pb_smad[keep_smad,]
de_results <- run_de_analysis(pb_smad, output_file = "myo_smad_gfp_DEGs.xlsx")
```

#Plotting gfp
```{r}

save_treatment_plots <- function(spe_list, prefix, outdir = "plots") {

  dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

  for (name_spe in names(spe_list)) {

    spe <- spe_list[[name_spe]]
    
    spe$in_treatment <- factor(
      as.character(spe$in_treatment),
      levels = c("0", "1"),
      labels = c("untreated", "treated")
    )

    # safety check
    cat("\nProcessing:", prefix, name_spe, "\n")
    print(table(spe$in_treatment, useNA = "ifany"))

    # plot
    p <- plotCoords(
      spe,
      annotate = "in_treatment"
    ) +
      ggtitle(name_spe) +
      scale_color_manual(
        values = c("untreated" = "grey", "treated" = "green"),
        labels = c("0" = "untreated", "1" = "treated"),
        name = "Treatment"
      ) +
      theme_bw()

    # save
    ggsave(
      filename = file.path(outdir, paste0(prefix, "_", name_spe, ".png")),
      plot = p,
      width = 6,
      height = 5,
      dpi = 300
    )
  }

  invisible(spe_list)
}

# run
fox0_list <- save_treatment_plots(fox0_list, "fox0")
murf_list <- save_treatment_plots(murf_list, "murf")
smad_list <- save_treatment_plots(smad_list, "smad")
```

#Plotting gfp value
```{r}
bin16_list_ann_gfp <- readRDS("~/bin16_list_ann_gfp.rds")
spe <- bin16_list_ann_gfp$c26foxO_b1

lapply()
plotCoords(spe, annotate = "gfp_value", )

# Itera sugli oggetti SpatialExperiment presenti nella lista
lista_grafici <- lapply(smad_list, function(spe_elem) {
  plotCoords(spe_elem, annotate = "gfp_value") +
    scale_color_gradient(low = "#e5f5e0", high = "#006d2c") # Gradiente dal verde chiaro al verde scuro
})

#GFP VALUE SU BLOCCO2 MISSING


```


