---
title: "GSEA"
output: html_document
date: "2025-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(SingleCellExperiment)
library(SummarizedExperiment)
library(scuttle)
library(edgeR)
library(RUVSeq)
library(scMerge)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(openxlsx)
library(dplyr)
library(stringr)
library(AnnotationDbi)
library(pathview)
library(muscat)
library(org.Mm.eg.db)
```

# TRIM C26 VS 2B SHAM 
```{r}
pb_16bin <- readRDS("~/pb_16bin.rds")
pb_16bin$group <- paste0(pb_16bin$new_cell_type, "_", pb_16bin$tissue_type)
pb_sub <- pb_16bin[, pb_16bin$group %in% c("Myonuclei_Trim63_c26", "Myonuclei_IIb_sham")]
pb_sub$group <- factor(pb_sub$group, levels = c("Myonuclei_IIb_sham", "Myonuclei_Trim63_c26"))

y <- DGEList(counts(pb_sub), samples = as.data.frame(colData(pb_sub)))
keep <- filterByExpr(y, group = y$samples$group)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
design <- model.matrix(~ group, data=y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = 2)
top <- topTags(lrt, n = Inf)$table
top$SYMBOL <- rownames(top)

top$significant <- top$FDR < 0.05
sig <- top[top$significant, ]
sig_up <- sig[sig$logFC >= 0, ]
sig_down <- sig[sig$logFC < 0, ]
  
gene_summary <- data.frame(
    Geni_considerati = nrow(top),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
)
  
gene_summary
  
```

#GSEA
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$tissue_type == "c26", 1, 0)

rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_trim_2b.xlsx", overwrite = TRUE)

```

# TRIM C26 VS MYONUCLEI OVERALL SHAM
```{r}
pb_16bin$group <- paste0(pb_16bin$new_cell_type, "_", pb_16bin$tissue_type)
mio_ov_sham <- unique(grep(paste0("^", "Myonuclei", ".*", "sham"), pb_16bin$group, value = TRUE))
pb_sub <- pb_16bin[, pb_16bin$group %in% c("Myonuclei_Trim63_c26", mio_ov_sham)]
pb_sub$group[pb_sub$group %in% mio_ov_sham] <- "Myonuclei_sham"
pb_sub$group <- as.factor(pb_sub$group)
pb_comb <- aggregateData(pb_sub, assay = "counts", fun = "sum", by = "sample_id")
colData(pb_comb)$group <- pb_sub$group[match(colnames(pb_comb), pb_sub$sample_id)]
names(assays(pb_comb)) <- "counts"

y <- DGEList(counts(pb_comb), samples = as.data.frame(colData(pb_comb)))
keep <- filterByExpr(y, group = y$samples$group)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
design <- model.matrix(~ group, data=y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = 2)
top <- topTags(lrt, n = Inf)$table
top$SYMBOL <- rownames(top)

top$significant <- top$FDR < 0.05
sig <- top[top$significant, ]
sig_up <- sig[sig$logFC >= 0, ]
sig_down <- sig[sig$logFC < 0, ]

gene_summary <- data.frame(
    Geni_considerati = nrow(top),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
)
  
gene_summary
  
```

#GSEA
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == "Myonuclei_Trim63_c26", 1, 0)

rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)

gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)
res_df <- as.data.frame(gsea_sig@result)

wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_trim_overall.xlsx", overwrite = TRUE)

```

# TRIM VS 2B NEI C26 
Adding a sample-specific effect to account not for technical variability (that we never considered
a real issue -> see pseudobulk pca) but to account for biological variability, as now we are 
making a comparison WITHIN condition (so we cannot presume independency).
```{r}
# pb_mult <- readRDS("~/pb_wb7.rds")
# pb_sub <- pb_mult[, pb_mult$tissue_type == "c26" &
#                     pb_mult$cell_type %in% c("Myonuclei_Trim63","Myonuclei_IIb")]
# pb_sub$group <- pb_sub$cell_type
# 
# y <- DGEList(counts(pb_sub), samples = as.data.frame(colData(pb_sub)))
# keep <- filterByExpr(y, group = y$samples$group)
# y <- y[keep,, keep.lib.sizes=FALSE]
# y <- calcNormFactors(y)
# design <- model.matrix(~ group + sample_id, data=y$samples)
# y <- estimateDisp(y, design)
# fit <- glmFit(y, design)
# lrt <- glmLRT(fit, coef = 2)
# top <- topTags(lrt, n = Inf)$table
# top$SYMBOL <- rownames(top)
# 
# top$significant <- top$FDR < 0.05
# sig <- top[top$significant, ]
# sig_up <- sig[sig$logFC >= 0, ]
# sig_down <- sig[sig$logFC < 0, ]
#   
# wb <- createWorkbook()
# addWorksheet(wb, "Tutti_geni")
# writeData(wb, "Tutti_geni", top, rowNames = TRUE)
# addWorksheet(wb, "Significativi")
# writeData(wb, "Significativi", sig, rowNames = TRUE)
# addWorksheet(wb, "Upregolati")
# writeData(wb, "Upregolati", sig_up, rowNames = TRUE)
# addWorksheet(wb, "Downregolati")
# writeData(wb, "Downregolati", sig_down, rowNames = TRUE)
# saveWorkbook(wb,"trim_2b_withinc26.xlsx", overwrite = TRUE)
#   
# gene_summary <- data.frame(
#     Geni_considerati = nrow(top),
#     Geni_significativi = nrow(sig),
#     Upregolati = nrow(sig_up),
#     Downregolati = nrow(sig_down)
# )
#   
# gene_summary

```
#GSEA
```{r}
# se <- SummarizedExperiment(assays = list(counts = y$counts),
#                              colData = y$samples)
# assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
# se$GROUP <- ifelse(se$group == "Myonuclei_Trim63", 1, 0)
# 
# rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
# rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
# rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
# rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]
# 
# geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
# geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]
# 
# make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
#   # SYMBOL -> ENTREZ
#   ids <- suppressMessages(
#     bitr(names(logFC_named_by_SYMBOL),
#          fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
#   )
#   v <- logFC_named_by_SYMBOL[ids$SYMBOL]
#   names(v) <- ids$ENTREZID
#   v <- v[!is.na(v) & !is.na(names(v))]
#   sort(v, decreasing = TRUE)
# }
# 
# geneList <- make_geneList_kegg(geneList)
# gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
#             pvalueCutoff = 0.05, verbose = FALSE)
# gsea_sig@result
# 
# convert_core_enrichment <- function(entrez_string) {
#   entrez_ids <- strsplit(entrez_string, "/")[[1]]
#   symbols <- bitr(entrez_ids, fromType="ENTREZID", 
#                   toType="SYMBOL", OrgDb= org.Mm.eg.db)
#   paste(symbols$SYMBOL, collapse="/")
# }
# gsea_sig@result$core_enrichment_symbols <- 
#   sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)
# res_df <- as.data.frame(gsea_sig@result)
# res_df
# 
# wb <- createWorkbook()
# addWorksheet(wb, "GSEA_Results")
# writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
# saveWorkbook(wb, file = "gsea_withinC26.xlsx", overwrite = TRUE)

```




