---
title: "GSEA_nuclei"
output: html_document
date: "2025-11-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(SingleCellExperiment)
library(SummarizedExperiment)
library(scuttle)
library(edgeR)
library(RUVSeq)
library(scMerge)
library(clusterProfiler)
library(enrichplot)
library(ggplot2)
library(openxlsx)
library(dplyr)
library(stringr)
library(AnnotationDbi)
library(pathview)
library(muscat)
library(org.Mm.eg.db)
library(SpatialExperiment)
library(SpatialFeatureExperiment)
library(purrr)
```

#DEG trim c26 vs 2b sham
```{r}
pb_nuclei <- readRDS("~/data/pb_nuclei.rds")
pb_nuclei$group <- paste0(pb_nuclei$cell_type, "_", pb_nuclei$sampletype)
pb_sub <- pb_nuclei[, pb_nuclei$group %in% c("Myonuclei_Trim63_c26", "Myonuclei_IIb_sham")]
pb_sub$group <- factor(pb_sub$group, levels = c("Myonuclei_IIb_sham", "Myonuclei_Trim63_c26"))

y <- DGEList(counts(pb_sub), samples = as.data.frame(colData(pb_sub)))
keep <- filterByExpr(y, group = y$samples$group)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
design <- model.matrix(~ group, data=y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = 2)
top <- topTags(lrt, n = Inf)$table
top$SYMBOL <- rownames(top)

top$significant <- top$FDR < 0.05
sig <- top[top$significant, ]
sig_up <- sig[sig$logFC >= 0, ]
sig_down <- sig[sig$logFC < 0, ]
  
gene_summary <- data.frame(
    Geni_considerati = nrow(top),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
)
  
gene_summary

```

#GSEA
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$sampletype == "c26", 1, 0)

rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)

#saving results
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_nuclei_trim_2b.xlsx", overwrite = TRUE)

```

```{r}
p <- enrichplot::dotplot(gsea_sig, showCategory = 15, font.size = 8,
                    title = "Enriched Pathways", split=".sign") + facet_grid(.~.sign)
ggsave("pathways_trim_2b.pdf", plot = p,
       width = 8, height = 9, dpi = 300)

#second plot 
enrich_KEGG <- as.data.frame(gsea_sig@result)
enrich_KEGG <- enrich_KEGG[order(enrich_KEGG$p.adjust), ]
enrich_KEGG <- enrich_KEGG[enrich_KEGG$p.adjust < 0.05, ]

enrich_KEGG$Count <- sapply(strsplit(enrich_KEGG$core_enrichment, "/"), length)
enrich_KEGG$GeneRatio <- enrich_KEGG$Count / enrich_KEGG$setSize

# separa i dati
enrich_pos <- enrich_KEGG[enrich_KEGG$NES > 0, ]
enrich_neg <- enrich_KEGG[enrich_KEGG$NES < 0, ]

# grafico positivi
p_pos <- ggplot(enrich_pos,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Positive Pathways")

ggsave("trim_2b_pos.pdf", plot = p_pos,
       width = 20, height = 9, dpi = 300)

# grafico negativi
p_neg <- ggplot(enrich_neg,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Negative Pathways")

ggsave("trim_2b_neg.pdf", plot = p_neg,
       width = 20, height = 9, dpi = 300)

```

#DEG trim vs overall
```{r}
pb_nuclei$group <- paste0(pb_nuclei$cell_type, "_", pb_nuclei$sampletype)
mio_ov_sham <- unique(grep(paste0("^", "Myonuclei", ".*", "sham"), pb_nuclei$group, value = TRUE))
pb_sub <- pb_nuclei[, pb_nuclei$group %in% c("Myonuclei_Trim63_c26", mio_ov_sham)]
pb_sub$group[pb_sub$group %in% mio_ov_sham] <- "Myonuclei_sham"
pb_sub$group <- as.factor(pb_sub$group)
pb_comb <- aggregateData(pb_sub, assay = "counts", fun = "sum", by = "sample_id")
colData(pb_comb)$group <- pb_sub$group[match(colnames(pb_comb), pb_sub$sample_id)]
names(assays(pb_comb)) <- "counts"

y <- DGEList(counts(pb_comb), samples = as.data.frame(colData(pb_comb)))
keep <- filterByExpr(y, group = y$samples$group)
y <- y[keep,, keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
design <- model.matrix(~ group, data=y$samples)
y <- estimateDisp(y, design)
fit <- glmFit(y, design)
lrt <- glmLRT(fit, coef = 2)
top <- topTags(lrt, n = Inf)$table
top$SYMBOL <- rownames(top)

top$significant <- top$FDR < 0.05
sig <- top[top$significant, ]
sig_up <- sig[sig$logFC >= 0, ]
sig_down <- sig[sig$logFC < 0, ]
  
gene_summary <- data.frame(
    Geni_considerati = nrow(top),
    Geni_significativi = nrow(sig),
    Upregolati = nrow(sig_up),
    Downregolati = nrow(sig_down)
)
  
gene_summary

```

#TRIM63+ C26 VS OVERALL SHAM
```{r}
se <- SummarizedExperiment(assays = list(counts = y$counts),
                             colData = y$samples)
assay(se, "norm") <- cpm(y, log = TRUE, prior.count = 1)
se$GROUP <- ifelse(se$group == c("Myonuclei_Trim63_c26"), 1, 0)

rowData(se)$PVAL     <- top$PValue[match(rownames(se), rownames(top))]
rowData(se)$FC       <- top$logFC[match(rownames(se), rownames(top))]
rowData(se)$ADJ.PVAL <- top$FDR[match(rownames(se), rownames(top))]
rowData(se)$SYMBOL   <- top$SYMBOL[match(rownames(se), rownames(top))]

geneList <- rowData(se)$FC; names(geneList) <- rowData(se)$SYMBOL
geneList <- geneList[!is.na(geneList) & !is.na(names(geneList))]

make_geneList_kegg <- function(logFC_named_by_SYMBOL) {
  # SYMBOL -> ENTREZ
  ids <- suppressMessages(
    bitr(names(logFC_named_by_SYMBOL),
         fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  )
  v <- logFC_named_by_SYMBOL[ids$SYMBOL]
  names(v) <- ids$ENTREZID
  v <- v[!is.na(v) & !is.na(names(v))]
  sort(v, decreasing = TRUE)
}

geneList <- make_geneList_kegg(geneList)
gsea_sig <- gseKEGG(geneList = geneList, organism = "mmu",
            pvalueCutoff = 0.05, verbose = FALSE, nPermSimple = 10000)
gsea_sig@result

convert_core_enrichment <- function(entrez_string) {
  entrez_ids <- strsplit(entrez_string, "/")[[1]]
  symbols <- bitr(entrez_ids, fromType="ENTREZID", 
                  toType="SYMBOL", OrgDb= org.Mm.eg.db)
  paste(symbols$SYMBOL, collapse="/")
}
gsea_sig@result$core_enrichment_symbols <- 
  sapply(gsea_sig@result$core_enrichment, convert_core_enrichment)

res_df <- as.data.frame(gsea_sig@result)
wb <- createWorkbook()
addWorksheet(wb, "GSEA_Results")
writeData(wb, sheet = "GSEA_Results", x = res_df, rowNames = TRUE)
saveWorkbook(wb, file = "gsea_nuclei_trim_overall.xlsx", overwrite = TRUE)

```

```{r}
pathways <- c("mmu00190","mmu04714","mmu01100","mmu04020","mmu04261","mmu00010","mmu04022","mmu04820",
              "mmu04137","mmu04150")
gsea_sig@result <- gsea_sig@result[gsea_sig@result$ID %in% pathways,]
p <- enrichplot::dotplot(gsea_sig, showCategory = 15, font.size = 10,
                    title = "Enriched Pathways", split=".sign") + facet_grid(.~.sign)
ggsave("pathways_trim_overall.pdf", plot = p,
       width = 8, height = 9, dpi = 300)

#second plot 
enrich_KEGG <- as.data.frame(gsea_sig@result)
enrich_KEGG <- enrich_KEGG[order(enrich_KEGG$p.adjust), ]
enrich_KEGG <- enrich_KEGG[enrich_KEGG$p.adjust < 0.05, ]

enrich_KEGG$Count <- sapply(strsplit(enrich_KEGG$core_enrichment, "/"), length)
enrich_KEGG$GeneRatio <- enrich_KEGG$Count / enrich_KEGG$setSize

# separa i dati
enrich_pos <- enrich_KEGG[enrich_KEGG$NES > 0, ]
enrich_neg <- enrich_KEGG[enrich_KEGG$NES < 0, ]

# grafico positivi
p_pos <- ggplot(enrich_pos,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_size_continuous(range = c(4, 10)) + 
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  theme(
    axis.text.y = element_text(size = 20), # Dimensione testo asse Y (le description)
    axis.text.x = element_text(size = 14), # Dimensione testo asse X
    axis.title = element_text(size = 16, face = "bold"), # Titoli degli assi
    plot.title = element_text(size = 18, face = "bold")  # Titolo del grafico
  ) +
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Positive Pathways")

ggsave("trim_overall_pos.pdf", plot = p_pos,
       width = 10, height = 9, dpi = 300)

# grafico negativi
p_neg <- ggplot(enrich_neg,
                aes(x = -log10(p.adjust),
                    y = reorder(Description, -log10(p.adjust)),
                    color = GeneRatio,
                    size = Count)) +
  geom_point() +
  scale_size_continuous(range = c(4, 10)) + 
  scale_color_gradient(low = "blue", high = "red") +
  theme_minimal(base_size = 16) +
  theme(
    axis.text.y = element_text(size = 17), # Dimensione testo asse Y (le description)
    axis.text.x = element_text(size = 14), # Dimensione testo asse X
    axis.title = element_text(size = 16, face = "bold"), # Titoli degli assi
    plot.title = element_text(size = 18, face = "bold")  # Titolo del grafico
  )
  ylab("Description") +
  xlab("-log10(p.adjust)") +
  ggtitle("KEGG Negative Pathways")

ggsave("trim_overall_neg.pdf", plot = p_neg,
       width = 20, height = 9, dpi = 300)

```



